DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
    STUDENT_ID  INT,
    Name VARCHAR(20),
    Major VARCHAR(20) DEFAULT'UNDICIDED',
    PRIMARY KEY (STUDENT_ID)


);
SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES (1, 'MZOBE', 'IT');
INSERT INTO STUDENT VALUES (2,'DEBABA','ENGINEERING');
INSERT INTO STUDENT VALUES (3,'GLORIA','CONSUMER');
INSERT INTO STUDENT VALUES (4,'THANDO','MOTOR');
INSERT INTO STUDENT VALUES (5,'SYA','WOODWORK');
INSERT INTO STUDENT (STUDENT_ID, NAME) VALUES (6,'THOBILE');
